name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: kubectl apply
        continue-on-error: true
        run: kubectl apply -f k8s-vm/
